// UIs/angular/projects/components/src/lib/task-edit/task-edit.component.ts
import { Task, TaskStatus } from '@airline/tasks';
import { Component, Input, OnInit, ViewChild } from '@angular/core';
import { IonModal } from '@ionic/angular';

@Component({
  selector: 'air-task-edit',
  templateUrl: './task-edit.component.html',
  styleUrls: ['./task-edit.component.css'],
})
export class TaskEditComponent implements OnInit {

  @ViewChild(IonModal)
  modal: IonModal = null as any

  @Input()
  task: Task = null as any

  @Input()
  onWillDismiss: (e: Event) => void = null as any

  @Input()
  triggerId: string = null as any

  TaskStatus = TaskStatus

  constructor() { }

  ngOnInit() { }

  cancel(): void {
    this.modal.dismiss(null, 'cancel')
  }

  save(): void {
    this.modal.dismiss(null, 'save')
  }

}

<ion-modal [trigger]="triggerId" (willDismiss)="onWillDismiss($event)">
  <ion-header>
    <ion-toolbar>
      <ion-buttons *ngIf="task">
        <ion-button (click)="cancel()" slot="start">
          Cancel
        </ion-button>
        <ion-title>{{task.id ? 'Edit' : 'Create'}}" Goal</ion-title>
        <ion-button (click)="save()" slot="end">
          Save
        </ion-button>
      </ion-buttons>
    </ion-toolbar>
  </ion-header>
  <ion-content className="ion-padding">
    <ion-item>
      <air-eisenhower-inputs [rankedUnit]="task"></air-eisenhower-inputs>
    </ion-item>
    <ion-item>
      <ion-label position="stacked">Name</ion-label>
      <ion-input [(ngModel)]="task.name"> </ion-input>
    </ion-item>
    <ion-item>
      <ion-label position="stacked">Task Status</ion-label>
      <ion-select [(ngModel)]="task.status">
        <ion-select-option [value]="TaskStatus.IN_PLANNING">
          In Planning
        </ion-select-option>
        <ion-select-option [value]="TaskStatus.PENDING">
          Pending
        </ion-select-option>
        <ion-select-option [value]="TaskStatus.IN_PROGRESS">
          In Progress
        </ion-select-option>
        <ion-select-option [value]="TaskStatus.DONE">
          Done
        </ion-select-option>
      </ion-select>
    </ion-item>
    <ion-item>
      <ion-label position="floating">Description</ion-label>
      <ion-textarea [(ngModel)]="task.description"
        ></ion-textarea>
    </ion-item>
  </ion-content>
</ion-modal>

// UIs/react/components/src/TaskEdit.tsx
import { Task } from "@airline/tasks";
import { OverlayEventDetail } from "@ionic/core";
import { IonButton, IonButtons, IonContent, IonHeader, IonInput, IonItem, IonLabel, IonModal, IonTextarea, IonTitle, IonToggle, IonToolbar } from "@ionic/react";
import { useRef } from "react";
import { TaskMatrix } from "./TaskMatrix";

export function TaskEdit({ task, triggerId }: { task: Task, triggerId: string }) {
    const modal = useRef<HTMLIonModalElement>(null);

    return (
        <IonModal ref={modal} trigger={triggerId}>
            <IonHeader>
                <IonToolbar>
                    <IonButtons slot="start">
                        <IonButton onClick={() => modal.current?.dismiss()}>Cancel</IonButton>
                    </IonButtons>
                    <IonTitle>{task.id ? 'Edit' : 'Create'} {task.isGoal ? 'Goal' : 'Task'}</IonTitle>
                    <IonButtons slot="end">
                        <IonButton strong={true} onClick={() => modal.current?.dismiss(task, 'confirm')}>
                            Confirm
                        </IonButton>
                    </IonButtons>
                </IonToolbar>
            </IonHeader>
            <IonContent className="ion-padding">
                <IonItem>
                    <TaskMatrix
                        task={task}
                    ></TaskMatrix>
                </IonItem>
                <IonItem>
                    <IonLabel>Is a goal</IonLabel>
                    <IonToggle checked={task.isGoal} onIonChange={e => task.isGoal = e.detail.checked} />
                </IonItem>
                <IonItem>
                    <IonLabel position="stacked">Name</IonLabel>
                    <IonInput
                        value={task.name}
                        onIonChange={e => task.name = e.detail.value as string}
                    > </IonInput>
                </IonItem>
                <IonItem>
                    <IonLabel position="floating">Description</IonLabel>
                    <IonTextarea
                        value={task.description}
                        onIonChange={e => task.description = e.detail.value as string}
                    ></IonTextarea>
                </IonItem>
            </IonContent>
        </IonModal>
    )
}
